[package]
name = "candle-llm-chat"
version = "0.5.1"
edition = "2024"

[lints.rust]
unused = { level = "allow", priority = 0 }

[dependencies]
anyhow = "1.0"
tokio = "1.52"
# intel-mkl-src = { version = "0.8", features = ["mkl-static-lp64-iomp"] }

candle = { package = "candle-core", version = "0.10" }
candle-nn = "0.10"
# feat mkl STATUS_DLL_NOT_FOUND
candle-transformers = { version = "0.10", features = [
    "cuda",
    "cudnn",
    # "flash-attn",
] }
candle-examples = "0.10"

hf-hub = { version = "0.5", features = ["tokio"] }
tokenizers = { version = "*", features = ["http"] }

async-stream = "0.3"
futures-core = "0.3"
futures-util = "0.3"

tracing = "0.1"

config = "0.15"
toml = "1.1"
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
serde_default_utils = { version = "0.3", features = ["inline"] }
derive-new = "0.7"
strum = { version = "0.28", features = ["derive"] }
minijinja = { version = "2.19", features = ["loader"] }
minijinja-contrib = { version = "2.19", features = ["pycompat"] }
regex = "1.12"
reqwest = { version = "0.13", features = ["blocking"] }
image = "0.24"

[dev-dependencies]
tracing-subscriber = "0.3"
futures-util = "0.3"
